---
- name: Install Python setuptools
  package:
    name: python-setuptools
    state: present

# Manage Repositories
- include_tasks: repos.yml
  when: scl_manage_repo

- include_tasks: wrappers.yml
  when: scl_wrappers | length > 0

- include_tasks: packages.yml
  when: scl_packages | length > 0

- include_tasks: gems.yml
  when: scl_ruby_gems | length > 0

- include_tasks: pips.yml
  when: scl_python_pips | length > 0
