- hosts: localhost
  become: true
  
  tasks:
    - name: "Install"
      ansible.builtin.yum: 
        name:
        - postgresql-devel
        - centos-release-scl
        - rh-ruby27
        - rubygems
        - ruby-devel
        state: present
        update_cache: True
        
    - name: "Add wrapper script for rh-ruby27"
      include_role:
        name: ansible-role-scl
        tasks_from: wrappers
      vars:
        scl_wrappers:
          - {collection: 'rh-ruby27', command: 'ruby'}

    - name: "Install rh-ruby27 from SCL"
      include_role:
        name: ansible-role-scl
        tasks_from: packages
      vars:
        scl_packages:
          - {name: 'rh-ruby27'}
    - name: "enable ruby 2.7"
      shell: "scl enable rh-ruby27 bash"
      
  roles:
    - nginx
    - postgresql
    - ruby_app